export default {
  FETCH_COUNTRY_NAMES: "FETCH_COUNTRY_NAMES",
  FETCH_COUNTRY_NAMES_SUCCESS: "FETCH_COUNTRY_NAMES_SUCCESS",
  GET_SELECTED_COUNTRY_INFO: "GET_SELECTED_COUNTRY_INFO",
  GET_SELECTED_COUNTRY_INFO_SUCCESS: "GET_SELECTED_COUNTRY_INFO_SUCCESS",
};
